[[upcoming]]
date = "2026-06-25"
time = "10:45am - 11:30am"
room = "Meeting Room F3, Building B"
topic = "Open source models via Ollama"
speaker = "Steffen Plunder"
abstract = """
Up until now, the most powerful AI models were closed and access either limited to external harness or extremely expensive. But recently released open weight models (notably GLM 5.2) change this, allowing to use frontier LLMs with open source tools and respect confidentiality.
"""

# Add past seminars here after they happen.
# [[past]]
# date = "2026-07-02"
# time = "11:30am - 12:15pm"
# room = "Seminar Room F1 ASHBi Building B"
# topic = "Example topic"
# speaker = "Example Speaker"
