[[upcoming]]
date = "2026-06-25"
time = "10:45am - 11:30am"
room = "Meeting Room F3, Building B"
topic = "OpenClaw/Hermes Agent: Secure Setup for AI Assistants"
speaker = "Steffen Plunder"
abstract = """
Can you write and run a complete analysis pipeline with a few LINE messages?
If you know your goal well enough, then probably yes.
I will show how to set up autonomous agents like OpenClaw or Hermes Agent in secure environments (NemoClaw)
and with open source models (Ollama).
"""

# Add past seminars here after they happen.
# [[past]]
# date = "2026-07-02"
# time = "11:30am - 12:15pm"
# room = "Seminar Room F1 ASHBi Building B"
# topic = "Example topic"
# speaker = "Example Speaker"
